version: '3.7'

networks: 
  news:

services:
    postgres:
      image: 'postgres:alpine'
      container_name: 'postgres'
      environment: 
        POSTGRES_DB: news_feed
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      restart: "unless-stopped"
      volumes:
        - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
        - db-data:/var/lib/postgresql/data
      networks: 
        - news
    news-parser:
      build: 
        context: "./"
        dockerfile: ./docker/news-parser.Dockerfile
      ports: 
        - "8000:8000"
      restart: "unless-stopped"
      depends_on:
        - postgres
      networks: 
        - news

volumes:
  db-data:
    driver: local